server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/coffechain
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jackson:
    serialization:
      fail-on-empty-beans: false
    default-property-inclusion: non_null

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  liquibase:
    change-log: classpath:db/changelog/master.yaml

logging:
  level:
    org:
      springframework.security: DEBUG
      com.fasterxml.jackson: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
